<?php
/**
 * @file
 * Handles entity support for Islandora.
 */

// Content models.
define('ISLANDORA_ENTITIES_PERSON_CONTENT_MODEL', 'islandora:personCModel');
define('ISLANDORA_ENTITIES_EVENT_CONTENT_MODEL', 'islandora:eventCModel');
define('ISLANDORA_ENTITIES_PLACE_CONTENT_MODEL', 'islandora:placeCModel');
define('ISLANDORA_ENTITIES_ORGANIZATION_CONTENT_MODEL', 'islandora:organizationCModel');

// Permissions.
define('ISLANDORA_ENTITIES_ADMINISTER_PERMISSION', 'administer islandora entities');

/**
 * Implements hook_permission().
 */
function islandora_entities_permission() {
  return array(
    ISLANDORA_ENTITIES_ADMINISTER_PERMISSION => array(
      'title' => t('Administer Islandora Entities'),
      'description' => t('Access Islandora Entities administration page.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_entities_menu() {
  return array(
    'islandora/entities/search/%' => array(
      'title' => 'Query Entities',
      'page callback' => 'islandora_entities_query_entities_callback',
      'page arguments' => array(3),
      'type' => MENU_CALLBACK,
      'file' => 'includes/callbacks.inc',
      'access arguments' => TRUE,
    ),
    'admin/islandora/entities' => array(
      'title' => 'Islandora Entities',
      'description' => 'Configure the Entities solution pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_entities_settings'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/admin.form.inc',
      'access arguments' => array(ISLANDORA_ENTITIES_ADMINISTER_PERMISSION),
    ),
    'islandora/object/%islandora_object/EAC_CPF' => array(
      'title' => 'EAC-CPF',
      'page callback' => 'islandora_entities_eac_cpf_view',
      'page arguments' => array(2),
      'type' => MENU_LOCAL_TASK,
      'access callback' => 'islandora_entities_access',
      'access arguments' => array(2),
    ),
  );
}
/**
 * Determine visibility of the EAC-CPF data.
 *
 * We have read-access to the EAC-CPF stream and a read-only form mapping.
 *
 * @param AbstractObject $object
 *   The Tuque object.
 *
 * @return bool
 *   TRUE if access is granted, FALSE otherwise.
 */
function islandora_entities_access(AbstractObject $object) {
  return isset($object['EAC-CPF']) && islandora_datastream_access(FEDORA_VIEW_OBJECTS, $object['EAC-CPF']) &&
    islandora_entities_get_cmodel_form_name($object);
}

/**
 * Generate markup to display the entity form.
 *
 * @param AbstractObject $object
 *   Fedora object to render the form for.
 */
function islandora_entities_eac_cpf_view(AbstractObject $object) {
  $block = array();
  $block['content'] = array(
    '#markup' => islandora_entities_eac_cpf_markup($object),
  );
  return $block;
}

/**
 * Return a rendured drupal from as html.
 *
 * @param AbstractObject $object
 *   The fedora object to generate the rendered html.
 *
 * @return unknown
 *   The rendered HTML for the given content form.
 */
function islandora_entities_eac_cpf_markup(AbstractObject $object) {
  $form = array(
    'collection_metadata' => array(),
  );
  if (isset($object['EAC-CPF'])) {
    $content = $object['EAC-CPF']->content;
    // We need to determine of entity relationship exists in the content model
    // relationships, and display the correct form.
    $metadata = drupal_get_form(islandora_entities_get_cmodel_form_name($object), $content);
    $form['collection_metadata']['metadata'] = $metadata;
  }
  $output = drupal_render($form);
  return $output;
}

/**
 * Get the correct form name based on the content model.
 *
 * @param AbstractObject $object
 *   The current relations for the given fedora object.
 *
 * @return string|bool
 *   A string containing the form name to display, or boolean FALSE if the
 *   we do not have a mapping.
 */
function islandora_entities_get_cmodel_form_name(AbstractObject $object) {
  $mapping = array(
    ISLANDORA_ENTITIES_PERSON_CONTENT_MODEL => 'Person EAC-CPF Read Only',
    ISLANDORA_ENTITIES_EVENT_CONTENT_MODEL => 'Event EAC-CPF Read Only',
    ISLANDORA_ENTITIES_PLACE_CONTENT_MODEL => 'Place EAC-CPF Read Only',
    ISLANDORA_ENTITIES_ORGANIZATION_CONTENT_MODEL => 'Organization EAC-CPF Read Only',
  );

  $matches = array_intersect($object->models, array_keys($mapping));
  $match = reset($matches);

  if ($match) {
    return $mapping[$match];
  }
  else {
    return FALSE;
  }
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_entities_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_event_form' => array(
      'content_model' => ISLANDORA_ENTITIES_EVENT_CONTENT_MODEL,
      'form_name' => 'Event EAC-CPF form',
      'dsid' => 'EAC-CPF',
      'title_field' => array(
        'cpfdesc',
        'general_ident',
        'ident',
        'name_entries',
        0,
        'forename',
      ),
      'transform' => 'eaccpf_to_dc.xsl',
      'template' => FALSE,
    ),
    'islandora_organization_form' => array(
      'content_model' => ISLANDORA_ENTITIES_ORGANIZATION_CONTENT_MODEL,
      'form_name' => 'Organization EAC-CPF form',
      'dsid' => 'EAC-CPF',
      'title_field' => array(
        'cpfdesc',
        'general_ident',
        'ident',
        'name_entries',
        0,
        'forename',
      ),
      'transform' => 'eaccpf_to_dc.xsl',
      'template' => FALSE,
    ),
    'islandora_place_form' => array(
      'content_model' => ISLANDORA_ENTITIES_PLACE_CONTENT_MODEL,
      'form_name' => 'Place EAC-CPF form',
      'dsid' => 'EAC-CPF',
      'title_field' => array(
        'cpfdesc',
        'general_ident',
        'ident',
        'name_entries',
        0,
        'forename',
      ),
      'transform' => 'eaccpf_to_dc.xsl',
      'template' => FALSE,
    ),
    'islandora_person_form' => array(
      'content_model' => ISLANDORA_ENTITIES_PERSON_CONTENT_MODEL,
      'form_name' => 'Person EAC-CPF form',
      'dsid' => 'EAC-CPF',
      'title_field' => array(
        'cpfdesc',
        'general_ident',
        'ident',
        'name_entries',
        0,
        'forename',
      ),
      'transform' => 'eaccpf_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_entities_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_entities');
  // Also load read only version's of the form.
  return array(
    'Person EAC-CPF Read Only' => array(
      'form_file' => "$module_path/xml/person_eac_cpf_read_only.xml",
    ),
    'Event EAC-CPF Read Only' => array(
      'form_file' => "$module_path/xml/event_eac_cpf_read_only.xml",
    ),
    'Place EAC-CPF Read Only' => array(
      'form_file' => "$module_path/xml/place_eac-cpf_read_only.xml",
    ),
    'Organization EAC-CPF Read Only' => array(
      'form_file' => "$module_path/xml/organization_eac_cpf_read_only.xml",
    ),
    'Event EAC-CPF form' => array(
      'form_file' => "$module_path/xml/event_eaccpf_form.xml",
    ),
    'Organization EAC-CPF form' => array(
      'form_file' => "$module_path/xml/organization_eaccpf_form.xml",
    ),
    'Person EAC-CPF form' => array(
      'form_file' => "$module_path/xml/person_eaccpf_form.xml",
    ),
    'Place EAC-CPF form' => array(
      'form_file' => "$module_path/xml/place_eaccpf_form.xml",
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_entities_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_entities');

  // Entity Content Model.
  $entity_content_model = $connection->repository->constructObject('islandora:entityCModel');
  $entity_content_model->owner = 'fedoraAdmin';
  $entity_content_model->label = 'Islandora Entity Content Model';
  $entity_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $ds_composite_datastream = $entity_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $ds_composite_datastream->label = 'DS-COMPOSITE-MODEL';
  $ds_composite_datastream->mimetype = 'text/xml';
  $ds_composite_datastream->setContentFromFile("$module_path/xml/islandora_entity_ds_composite_model.xml", FALSE);
  $entity_content_model->ingestDatastream($ds_composite_datastream);

  // Person Content Model.
  $person_content_model = $connection->repository->constructObject('islandora:personCModel');
  $person_content_model->owner = 'fedoraAdmin';
  $person_content_model->label = 'Islandora Person Content Model';
  $person_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $person_content_model->ingestDatastream($ds_composite_datastream);

  // Place Content Model.
  $place_content_model = $connection->repository->constructObject('islandora:placeCModel');
  $place_content_model->owner = 'fedoraAdmin';
  $place_content_model->label = 'Islandora Place Content Model';
  $place_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $place_content_model->ingestDatastream($ds_composite_datastream);

  // Event Content Model.
  $event_content_model = $connection->repository->constructObject('islandora:eventCModel');
  $event_content_model->owner = 'fedoraAdmin';
  $event_content_model->label = 'Islandora Event Content Model';
  $event_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $event_content_model->ingestDatastream($ds_composite_datastream);

  // Organization Content Model.
  $organization_content_model = $connection->repository->constructObject('islandora:organizationCModel');
  $organization_content_model->owner = 'fedoraAdmin';
  $organization_content_model->label = 'Islandora Organization Content Model';
  $organization_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $organization_content_model->ingestDatastream($ds_composite_datastream);

  // Entity Collection.
  $entity_collection = $connection->repository->constructObject('islandora:entity_collection');
  $entity_collection->owner = 'fedoraAdmin';
  $entity_collection->label = 'Entity Collection';
  $entity_collection->models = 'islandora:collectionCModel';
  $entity_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // TN Datastream.
  $thumbnail_datastream = $entity_collection->constructDatastream('TN', 'M');
  $thumbnail_datastream->label = 'Thumbnail';
  $thumbnail_datastream->mimetype = 'image/png';
  $thumbnail_datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $entity_collection->ingestDatastream($thumbnail_datastream);
  // Collection policy datastream.
  $collection_policy_datastream = $entity_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $collection_policy_datastream->label = 'Collection policy';
  $collection_policy_datastream->mimetype = 'text/xml';
  $collection_policy_datastream->setContentFromFile("$module_path/xml/islandora_entity_collection_policy.xml", FALSE);
  $entity_collection->ingestDatastream($collection_policy_datastream);

  return array(
    'islandora_entity' => array(
      'title' => 'Islandora entity',
      'objects' => array(
        $entity_content_model,
        $place_content_model,
        $person_content_model,
        $event_content_model,
        $organization_content_model,
        $entity_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_entities_islandora_personCModel_islandora_object_ingested(AbstractObject $fedora_object) {
  module_load_include('inc', 'islandora_entities', 'includes/utilities');
  islandora_entities_add_entity_content_model($fedora_object);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_entities_islandora_placeCModel_islandora_object_ingested(AbstractObject $fedora_object) {
  module_load_include('inc', 'islandora_entities', 'includes/utilities');
  islandora_entities_add_entity_content_model($fedora_object);
}
/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_entities_islandora_eventCModel_islandora_object_ingested(AbstractObject $fedora_object) {
  module_load_include('inc', 'islandora_entities', 'includes/utilities');
  islandora_entities_add_entity_content_model($fedora_object);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_entities_islandora_organizationCModel_islandora_object_ingested(AbstractObject $fedora_object) {
  module_load_include('inc', 'islandora_entities', 'includes/utilities');
  islandora_entities_add_entity_content_model($fedora_object);
}

/**
 * Implements hook_islandora_xml_form_builder_get_transforms().
 */
function islandora_entities_islandora_xml_form_builder_get_transforms() {
  $module_path = drupal_get_path('module', 'islandora_entities');
  return array(
    'eaccpf_to_dc.xslt' => "$module_path/xml/eaccpf_to_dc.xslt",
  );
}
